name: Run UiPath Test on Push

on:
  push:
    branches: [ main ] # Change this to your default branch if different

jobs:
  run-uipath-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run UiPath Test
      id: run-test
      uses: UiPath/action-orchestrator@v1
      with:
        orchestrator_url: "https://platform.uipath.com" # Default UiPath Orchestrator URL
        orchestrator_tenant: ${{ secrets.TEN }}
        orchestrator_account: ${{ secrets.UI_ACC }}
        orchestrator_client_id: ${{ secrets.UI_ID }}
        orchestrator_client_secret: ${{ secrets.UI_SECRET }}
        process_name: "digitPass_US"
        process_type: "Test"
        folder_organization_unit: "Default" # Change to your folder if different
        strategy: "Specific"
        
    - name: Check job status
      run: |
        if [ "${{ steps.run-test.outputs.status }}" != "Successful" ]; then
          echo "UiPath test failed with status: ${{ steps.run-test.outputs.status }}"
          exit 1
        fi