name: Run UiPath Test on Push

on:
  push:
    branches: [ main ]  # Change if your default branch is different

jobs:
  run-uipath-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout the code (required for GitHub Actions)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install UiPath CLI (official method)
      - name: Setup UiPath CLI
        uses: uipath/setup-uipath-cli@v1
        with:
          version: 'latest'  # or pin to a specific version like '23.10'

      # 3. Authenticate with Orchestrator
      - name: Authenticate
        run: |
          uipath config set --orchestratorUrl "https://platform.uipath.com" --account ${{ secrets.UI_ACC }} --tenant ${{ secrets.TEN }}
          uipath auth login --clientId ${{ secrets.UI_ID }} --clientSecret ${{ secrets.UI_SECRET }}

      # 4. Run the UiPath Test
      - name: Execute Test Case
        run: |
          uipath test run --name "digitPass_US" --folder "Default"  # Adjust folder if needed