name: Run UiPath Test on Push

on:
  push:
    branches: [ main ]

jobs:
  run-uipath-test:
    runs-on: windows-latest  # UiPath CLI works better on Windows runners
    
    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install .NET (required for UiPath CLI)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # 3. Install UiPath CLI via NuGet
      - name: Install UiPath CLI
        run: |
          dotnet tool install --global UiPath.CLI --version 23.10.0
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # 4. Authenticate with Orchestrator
      - name: Authenticate
        run: |
          uipath config set --orchestratorUrl "https://platform.uipath.com" --account ${{ secrets.UI_ACC }} --tenant ${{ secrets.TEN }}
          uipath auth login --clientId ${{ secrets.UI_ID }} --clientSecret ${{ secrets.UI_SECRET }}

      # 5. Run the UiPath Test
      - name: Execute Test Case
        run: |
          uipath test run --name "digitPass_US" --folder "Default"