name: Run UiPath Test on Push

on:
  push:
    branches: [ main ]  # Change if needed

jobs:
  run-uipath-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install .NET (required for UiPath CLI)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # UiPath CLI requires .NET 6+

      # 3. Manually download & install UiPath CLI
      - name: Install UiPath CLI
        run: |
          # Download the latest UiPath CLI
          curl -L "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.0" -o uipath-cli.zip
          mkdir -p ~/.uipath
          unzip uipath-cli.zip -d ~/.uipath/cli
          echo "$HOME/.uipath/cli" >> $GITHUB_PATH  # Add to PATH

      # 4. Authenticate with Orchestrator
      - name: Authenticate
        run: |
          uipath config set --orchestratorUrl "https://platform.uipath.com" --account ${{ secrets.UI_ACC }} --tenant ${{ secrets.TEN }}
          uipath auth login --clientId ${{ secrets.UI_ID }} --clientSecret ${{ secrets.UI_SECRET }}

      # 5. Run the UiPath Test
      - name: Execute Test Case
        run: |
          uipath test run --name "digitPass_US" --folder "Default"